# -*- coding: utf-8 -*-
"""Copy of BCG-GEN AI Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggB9ooKWq8lf33dbXcF3gw-Z85pMHuMI
"""

from google.colab import drive
drive.mount('/content/drive')

"""## **Importing the necessary Modules**"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

"""## **Reading the Manually Extracted Dataset from SEC's EDGAR's database**
## **https://www.sec.gov/edgar/searchedgar/**
"""

data = pd.read_csv('/content/drive/MyDrive/BCG-GENAI/Final_report.csv')

data

"""## **Calculating Year-by-Year growth rates for Total Revenue and Net Income**"""

data['Revenue Growth (%)'] = data.groupby('Company')['Total Revenue'].pct_change() * 100
data['Net Income Growth (%)'] = data.groupby('Company')['Net Income'].pct_change() * 100

data

"""## **Imputing Null/NaN values that result from pct_change calculations with 0**"""

data.fillna(0, inplace=True)

data

"""## **Calculating Year-by-Year growth rates for Total Assets, Total Liabilities and Cash flow from Operations Activities**"""

data['Assets Growth (%)'] = data.groupby('Company')['Total Assets'].pct_change() * 100
data['Liabilities Growth (%)'] = data.groupby('Company')['Total Liabilities'].pct_change() * 100
data['Cash Flow from Operations Growth(%)'] = data.groupby('Company')['Cash Flow from Operating Activities'].pct_change() * 100

data

data.fillna(0, inplace=True)

data

# Add a filename to the path, like 'data.csv'
data.to_csv('/content/drive/MyDrive/BCG-GENAI/final_data_report.csv')

summary = data.groupby('Company').agg({
    'Revenue Growth (%)': 'mean',
    'Net Income Growth (%)': 'mean',
    'Assets Growth (%)' : 'mean',
    'Liabilities Growth (%)' : 'mean',
    'Cash Flow from Operations Growth(%)' :'mean'
}).reset_index()

print('Year-By-Year Average Growth Rates(%) :-')
print('             OR')
print("Overall Growth/Fall rate for Apple, Microsoft and Tesla from Fiscal Year 2021 - 2023")
summary

summary.to_csv('/content/drive/MyDrive/BCG-GENAI/Summary_final_report.csv')

