# -*- coding: utf-8 -*-
"""Testing of AI Driven Financial Chatbot Prototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1do5VcM6L8rDORGtr66noM3cPteDfJ-oj

# The AI powered Financial Chatbot Prototype currently responds only to the given set of questions for selected companies and fiscal years wiz: --
# What is the total revenue?
# What is the Net Income?
# What is the sum of total assets?
# What is the sum of total liabilities?
# What is cash flow from operating activities?
# What is the revenue growth(%) ?
# What is the net income growth(%) ?
# What is the assets growth(%) ?
# What is the liabilities growth(%) ?
# What is the cash flow from operations growth(%) ?
# What is the year by year average revenue growth rate(%)?
# What is the year by year average net income growth rate(%)?
# What is the year by year average assets growth rate(%)?
# What is the year by year average liabilities growth rate(%)?
# What is the year by year average cash flow from operations growth rate(%)?
"""

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/BCG-GENAI/final_data_report.csv')
data_2 = pd.read_csv('/content/drive/MyDrive/BCG-GENAI/Summary_final_report.csv')

data

print("Year by Year Average Growth from 2021 to 2023")
data_2

# Commented out IPython magic to ensure Python compatibility.
# %run /content/drive/MyDrive/BCG-GENAI/ai_driven_financial_chatbot_prototype_python_application.py